[package]
name = "model-launcher-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
model-launcher-core = { path = "../model-launcher-core" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
copypasta = "0.10"
sha2 = "0.10"
slint.workspace = true

[build-dependencies]
slint-build = "=1.16.1"

[target.'cfg(windows)'.dependencies]
tray-icon = "0.21"

[dev-dependencies]
tempfile = "3"
